---
kind: Service
apiVersion: v1
metadata:
  name: doks-example
spec:
  type: LoadBalancer
  selector:
    app: doks-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ptz
      protocol: TCP
      port: 8031
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example
spec:
  replicas: 6
  selector:
    matchLabels:
      app: doks-example
  template:
    metadata:
      labels:
        app: doks-example
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
      - name: nigelpoulton
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080
          protocol: TCP
          