apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: birra
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: birra
spec:
  commonName: birra.pt
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
