apiVersion: v1
kind: Service
metadata:
  name: mysandbox-pw
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mysandbox-pw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysandbox-pw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysandbox-pw
  template:
    metadata:
      labels:
        app: mysandbox-pw
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: This is My Sandbox