apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: "GqwPdc2sTJw3B8NLQdkkO0awClCk5HgawSTx13PfDQ75YMZKl8pNnGFYuxkeYwui"
  network: "53142"
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
  namespace: kube-system
stringData:
  token: "GqwPdc2sTJw3B8NLQdkkO0awClCk5HgawSTx13PfDQ75YMZKl8pNnGFYuxkeYwui"