apiVersion: v1
kind: Service
metadata:
  name: birraapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: birraapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birraapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birraapi
  template:
    metadata:
      labels:
        app: birraapi
    spec:
      containers:
      - name: birraapi
        image: ptorrezao/birraapi:latest
        ports:
        - containerPort: 80
        env:
          - name: Database__Server
            value: mysql-service
          - name: Database__Port
            value: "3306"
          - name: Database__User
            value: "root"
          - name: Database__Database
            value: "APIDb"
          - name: Database__Password
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: ROOT_PASSWORD